# Generated by Django 2.2.3 on 2020-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Middlename', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('SSC_marks', models.IntegerField()),
                ('Diploma_marks', models.IntegerField()),
                ('BE_marks', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
